% This is an autogenerated sample test for file LogisticsRegression.m
classdef testLogisticsRegression < matlab.unittest.TestCase

    methods (Test)

        function test_LogisticsRegression(testCase)
            % Exercise the script LogisticsRegression
            LogisticsRegression;
        end
    end
end