% This is an autogenerated sample test for file SVMWeights.m
classdef testSVMWeights < matlab.unittest.TestCase

    methods (Test)

        function test_SVMWeights(testCase)
            % Exercise the script SVMWeights
            SVMWeights;
        end
    end
end